/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author AD
 */
public class ManHinhChinhView extends javax.swing.JPanel {

    DangNhapView dn = new DangNhapView();

    /**
     * Creates new form ManHinhChinhView
     */
    public ManHinhChinhView() {
        initComponents();
        this.setDefaultLocale(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanerC = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        QLLD = new javax.swing.JButton();
        QLDA = new javax.swing.JButton();
        QLHDView = new javax.swing.JButton();
        QLCV = new javax.swing.JButton();
        ThongKe = new javax.swing.JButton();
        Banner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NguoiDung = new javax.swing.JButton();
        DangXuat = new javax.swing.JButton();
        Hien = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1000, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        QLLD.setText("Quản lý lao động");
        QLLD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLLDActionPerformed(evt);
            }
        });

        QLDA.setText("Quản lý dự án");
        QLDA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLDAActionPerformed(evt);
            }
        });

        QLHDView.setText("Quản lý hợp đồng");
        QLHDView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QLHDView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLHDViewActionPerformed(evt);
            }
        });

        QLCV.setText("Quản lý công việc");
        QLCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLCVActionPerformed(evt);
            }
        });

        ThongKe.setText("Thống kê");
        ThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QLLD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QLDA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QLHDView, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(QLCV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(QLLD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(QLDA, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(QLHDView, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(QLCV, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        Banner.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/banner.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Chào mừng, Vũ Minh Duy đã quay lại trang quản lý!");

        NguoiDung.setBackground(new java.awt.Color(51, 51, 255));
        NguoiDung.setForeground(new java.awt.Color(255, 255, 255));
        NguoiDung.setText("Xem thông tin");
        NguoiDung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NguoiDungActionPerformed(evt);
            }
        });

        DangXuat.setBackground(new java.awt.Color(255, 102, 102));
        DangXuat.setForeground(new java.awt.Color(255, 255, 255));
        DangXuat.setText("Đăng Xuất");
        DangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BannerLayout = new javax.swing.GroupLayout(Banner);
        Banner.setLayout(BannerLayout);
        BannerLayout.setHorizontalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NguoiDung, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        BannerLayout.setVerticalGroup(
            BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(NguoiDung)
                    .addComponent(DangXuat))
                .addContainerGap())
        );

        javax.swing.GroupLayout HienLayout = new javax.swing.GroupLayout(Hien);
        Hien.setLayout(HienLayout);
        HienLayout.setHorizontalGroup(
            HienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );
        HienLayout.setVerticalGroup(
            HienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanerCLayout = new javax.swing.GroupLayout(PanerC);
        PanerC.setLayout(PanerCLayout);
        PanerCLayout.setHorizontalGroup(
            PanerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanerCLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanerCLayout.setVerticalGroup(
            PanerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanerCLayout.createSequentialGroup()
                .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanerCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Hien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanerC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanerC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangXuatActionPerformed

        JOptionPane.showMessageDialog(Banner, "Bạn có muốn đăng xuất không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        this.setVisible(false);
        dn.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_DangXuatActionPerformed

    private void NguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NguoiDungActionPerformed
        NguoiDungView nd = new NguoiDungView();
        nd.setSize(744, 600);
        nd.setLocation(0, 0);
        Hien.removeAll();
        Hien.add(nd, BorderLayout.CENTER);
        Hien.revalidate();
        Hien.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_NguoiDungActionPerformed

    private void QLLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLLDActionPerformed
        QLLDView qlld = new QLLDView();
        qlld.setSize(744, 600);
        qlld.setLocation(0, 0);
        Hien.removeAll();
        Hien.add(qlld, BorderLayout.CENTER);
        Hien.revalidate();
        Hien.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_QLLDActionPerformed

    private void QLHDViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLHDViewActionPerformed
        QLHDView qlhd = new QLHDView();
        qlhd.setSize(744, 600);
        qlhd.setLocation(0, 0);
        Hien.removeAll();
        Hien.add(qlhd, BorderLayout.CENTER);
        Hien.revalidate();
        Hien.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_QLHDViewActionPerformed

    private void QLDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLDAActionPerformed
        QLDAView qlda = new QLDAView();
        qlda.setSize(744, 600);
        qlda.setLocation(0, 0);
        Hien.removeAll();
        Hien.add(qlda, BorderLayout.CENTER);
        Hien.revalidate();
        Hien.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_QLDAActionPerformed

    private void QLCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLCVActionPerformed
        QLCVView qlcv = new QLCVView();
        qlcv.setSize(744, 600);
        qlcv.setLocation(0, 0);
        Hien.removeAll();
        Hien.add(qlcv, BorderLayout.CENTER);
        Hien.revalidate();
        Hien.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_QLCVActionPerformed

    private void ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongKeActionPerformed
        ThongKeView tk = new ThongKeView();
        tk.setSize(744, 600);
        tk.setLocation(0, 0);
        Hien.removeAll();
        Hien.add(tk, BorderLayout.CENTER);
        Hien.revalidate();
        Hien.repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_ThongKeActionPerformed

//    public static void run() {
//        /* Set the Nimbus look and feel */
//        try {
//            for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){//????m ý ebebn
//                if ("".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
//        java.util.logging.Logger.getLogger(DangNhapView.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new ManHinhChinhView().setVisible(true);
//        });
//    }
    public static void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.out.println("???");
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ManHinhChinhView().setVisible(true);

        });
    }public static void main(String[] args) {
        new ManHinhChinhView().setVisible(true);
    }// ??? m làm gì nó rồi sao nó k lên

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Banner;
    private javax.swing.JButton DangXuat;
    private javax.swing.JPanel Hien;
    private javax.swing.JButton NguoiDung;
    private javax.swing.JPanel PanerC;
    private javax.swing.JButton QLCV;
    private javax.swing.JButton QLDA;
    private javax.swing.JButton QLHDView;
    private javax.swing.JButton QLLD;
    private javax.swing.JButton ThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
